# Generated by Django 3.2.8 on 2021-11-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20211103_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='membersNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='private',
            field=models.CharField(choices=[('1', 'private'), ('2', 'public')], default='1', max_length=9),
        ),
    ]
