# Generated by Django 3.2.8 on 2021-11-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20211117_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='private',
            field=models.CharField(choices=[('1', 'private'), ('2', 'public')], default='2', max_length=9),
        ),
    ]
